/**
 * Test suite for automatic evidence ID registration in evidence ledger
 * 
 * Tests Issue 1 fix: Evidence IDs generated by recordPlanResult() should be
 * automatically registered in the evidence ledger so they can be validated
 * in mediation decisions.
 */

import { ParallelReasoningSessionManager } from '../src/workers/parallel-reasoning-mcp.js';
import { EvidenceLedger } from '../src/workers/evidence-ledger.js';

describe('Evidence ID Registration', () => {
  let manager: ParallelReasoningSessionManager;
  let ledger: EvidenceLedger;
  const sessionId = 'test-session-evidence';

  beforeEach(() => {
    manager = new ParallelReasoningSessionManager();
    ledger = new EvidenceLedger();
    
    // Configure manager with evidence ledger
    manager.setEvidenceLedger(ledger);

    // Initialize session
    manager.initSession({
      session_id: sessionId,
      task_description: 'Test evidence registration',
      required_diversity_axes: ['data_sources', 'analytical_models'],
      min_plans: 2
    });

    // Submit two plans
    manager.submitPlan(sessionId, {
      plan_id: 'plan-a',
      description: 'Plan A with quantitative analysis',
      diversity_axes: ['data_sources', 'analytical_models'],
      capability_chain: ['cap1', 'cap2', 'cap3', 'cap4', 'cap5', 'cap6', 'cap7', 'cap8'],
      rationale: 'Uses official statistics and regression models',
      expected_outputs: ['Market size', 'Growth forecast']
    });

    const planBResult = manager.submitPlan(sessionId, {
      plan_id: 'plan-b',
      description: 'Plan B with qualitative analysis',
      diversity_axes: ['data_sources', 'analytical_models', 'risk_perspectives', 'stakeholder_views'],
      capability_chain: ['cap1', 'cap2', 'cap3', 'cap4', 'cap5', 'cap6', 'cap7', 'cap8'],
      rationale: 'Uses expert interviews and stakeholder perspectives with risk analysis',
      expected_outputs: ['Stakeholder map', 'Pain points', 'Risk assessment']
    });

    // Verify plan-b was accepted
    if (!planBResult.accepted) {
      throw new Error(`Plan B was rejected: ${planBResult.reason}`);
    }
  });

  describe('recordPlanResult with evidence ledger', () => {
    it('should automatically register evidence ID in ledger', () => {
      // Record a result
      const result = {
        task: 'Market sizing analysis',
        summary: 'Market size is €2.5B',
        confidence: 0.85
      };

      const evidenceId = manager.recordPlanResult(sessionId, 'plan-a', result);

      // Verify evidence ID format
      expect(evidenceId).toBe(`${sessionId}:plan-a:step1`);

      // Verify evidence is registered in ledger
      const entry = ledger.getEntry(evidenceId);
      expect(entry).toBeDefined();
      expect(entry?.id).toBe(evidenceId);
      expect(entry?.claim).toContain('Market sizing analysis');
    });

    it('should register multiple evidence IDs sequentially', () => {
      const result1 = { task: 'Task 1', confidence: 0.8 };
      const result2 = { task: 'Task 2', confidence: 0.9 };
      const result3 = { task: 'Task 3', confidence: 0.7 };

      const evidenceId1 = manager.recordPlanResult(sessionId, 'plan-a', result1);
      const evidenceId2 = manager.recordPlanResult(sessionId, 'plan-a', result2);
      const evidenceId3 = manager.recordPlanResult(sessionId, 'plan-a', result3);

      expect(evidenceId1).toBe(`${sessionId}:plan-a:step1`);
      expect(evidenceId2).toBe(`${sessionId}:plan-a:step2`);
      expect(evidenceId3).toBe(`${sessionId}:plan-a:step3`);

      // All should be in ledger
      expect(ledger.getEntry(evidenceId1)).toBeDefined();
      expect(ledger.getEntry(evidenceId2)).toBeDefined();
      expect(ledger.getEntry(evidenceId3)).toBeDefined();
    });

    it('should register evidence for different plans', () => {
      // Verify both plans exist
      const session = manager.getSession(sessionId);
      expect(session).toBeDefined();
      expect(session?.plans.has('plan-a')).toBe(true);
      expect(session?.plans.has('plan-b')).toBe(true);

      const resultA = { task: 'Plan A task', confidence: 0.8 };
      const resultB = { task: 'Plan B task', confidence: 0.9 };

      const evidenceIdA = manager.recordPlanResult(sessionId, 'plan-a', resultA);
      const evidenceIdB = manager.recordPlanResult(sessionId, 'plan-b', resultB);

      expect(evidenceIdA).toBe(`${sessionId}:plan-a:step1`);
      expect(evidenceIdB).toBe(`${sessionId}:plan-b:step1`);

      expect(ledger.getEntry(evidenceIdA)).toBeDefined();
      expect(ledger.getEntry(evidenceIdB)).toBeDefined();
    });
  });

  describe('mediation decision validation with registered evidence', () => {
    it('should accept mediation decision with registered evidence IDs', () => {
      // Verify both plans exist
      const session = manager.getSession(sessionId);
      expect(session).toBeDefined();
      expect(session?.plans.has('plan-a')).toBe(true);
      expect(session?.plans.has('plan-b')).toBe(true);

      // Record some results
      const result1 = { task: 'Analysis 1', confidence: 0.85 };
      const result2 = { task: 'Analysis 2', confidence: 0.90 };

      const evidenceId1 = manager.recordPlanResult(sessionId, 'plan-a', result1);
      const evidenceId2 = manager.recordPlanResult(sessionId, 'plan-b', result2);

      // Create validator function
      const validateEvidenceIds = (ids: string[]) => {
        for (const id of ids) {
          const entry = ledger.getEntry(id);
          if (!entry) {
            return false;
          }
        }
        return true;
      };

      // Submit mediation decision with registered evidence IDs
      expect(() => {
        manager.submitMediationDecision(
          sessionId,
          {
            decision_point: 'Market sizing approach',
            chosen_from_plan: 'plan-a',
            rationale: 'Plan A provides more quantitative backing',
            evidence_ids: [evidenceId1, evidenceId2],
            confidence: 0.85
          },
          validateEvidenceIds
        );
      }).not.toThrow();
    });

    it('should reject mediation decision with non-existent evidence IDs', () => {
      // Record one result
      const result1 = { task: 'Analysis 1', confidence: 0.85 };
      const evidenceId1 = manager.recordPlanResult(sessionId, 'plan-a', result1);

      // Create validator function
      const validateEvidenceIds = (ids: string[]) => {
        for (const id of ids) {
          const entry = ledger.getEntry(id);
          if (!entry) {
            return false;
          }
        }
        return true;
      };

      // Try to submit mediation decision with fake evidence ID
      expect(() => {
        manager.submitMediationDecision(
          sessionId,
          {
            decision_point: 'Market sizing approach',
            chosen_from_plan: 'plan-a',
            rationale: 'Plan A provides more quantitative backing',
            evidence_ids: [evidenceId1, 'fake-evidence-id'],
            confidence: 0.85
          },
          validateEvidenceIds
        );
      }).toThrow('non-existent evidence IDs');
    });

    it('should work without evidence ledger (backward compatibility)', () => {
      // Create manager without evidence ledger
      const managerWithoutLedger = new ParallelReasoningSessionManager();
      
      managerWithoutLedger.initSession({
        session_id: 'test-no-ledger',
        task_description: 'Test without ledger',
        required_diversity_axes: ['data_sources', 'analytical_models'],
        min_plans: 2
      });

      managerWithoutLedger.submitPlan('test-no-ledger', {
        plan_id: 'plan-x',
        description: 'Plan X',
        diversity_axes: ['data_sources', 'analytical_models'],
        capability_chain: ['cap1', 'cap2', 'cap3', 'cap4', 'cap5', 'cap6', 'cap7', 'cap8'],
        rationale: 'Test plan',
        expected_outputs: ['Output']
      });

      // Should still generate evidence ID
      const result = { task: 'Task', confidence: 0.8 };
      const evidenceId = managerWithoutLedger.recordPlanResult('test-no-ledger', 'plan-x', result);
      
      expect(evidenceId).toBe('test-no-ledger:plan-x:step1');

      // Should accept mediation decision without validator
      expect(() => {
        managerWithoutLedger.submitMediationDecision(
          'test-no-ledger',
          {
            decision_point: 'Test decision',
            chosen_from_plan: 'plan-x',
            rationale: 'Test rationale',
            evidence_ids: [evidenceId],
            confidence: 0.8
          }
        );
      }).not.toThrow();
    });
  });

  describe('evidence ledger integration', () => {
    it('should store evidence with correct structure', () => {
      const result = {
        task: 'Market analysis',
        summary: 'Market size is €2.5B with 15% CAGR',
        confidence: 0.85,
        details: { size: 2500000000, cagr: 0.15 }
      };

      const evidenceId = manager.recordPlanResult(sessionId, 'plan-a', result);
      const entry = ledger.getEntry(evidenceId);

      expect(entry).toBeDefined();
      expect(entry?.artifact_id).toBe(evidenceId);
      expect(entry?.field_path).toBe('capability_result');
      expect(entry?.claim).toContain('Market analysis');
      expect(entry?.evidence).toHaveLength(1);
      expect(entry?.evidence[0].type).toBe('CALCULATION');
      expect(entry?.verification_status).toBe('unverified');
    });

    it('should handle missing task in result gracefully', () => {
      const result = {
        summary: 'Some summary',
        confidence: 0.75
      };

      const evidenceId = manager.recordPlanResult(sessionId, 'plan-a', result);
      const entry = ledger.getEntry(evidenceId);

      expect(entry).toBeDefined();
      // When task is missing, claim should use summary or fallback to plan execution message
      expect(entry?.claim).toBeTruthy();
      expect(entry?.claim.length).toBeGreaterThan(0);
    });
  });
});

